CREATE TABLE IF NOT EXISTS `po_images` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_property` BIGINT UNSIGNED NOT NULL,
    `id_building` BIGINT UNSIGNED NULL,
    `id_room` BIGINT UNSIGNED NULL,
    `id_feature` BIGINT UNSIGNED NULL,
    `type` VARCHAR(50) NOT NULL DEFAULT 'general',
    `placement` VARCHAR(50) NULL,
    `filename` VARCHAR(255) NOT NULL,
    `alt` VARCHAR(255) NULL,
    `title` VARCHAR(255) NULL,
    `description` TEXT NULL,
    `metadata` JSON NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_property` (`id_property`),
    KEY `idx_building` (`id_building`),
    KEY `idx_room` (`id_room`),
    KEY `idx_feature` (`id_feature`),
    KEY `idx_type` (`type`),
    CONSTRAINT `fk_po_images_property` FOREIGN KEY (`id_property`) REFERENCES `properties` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_po_images_building` FOREIGN KEY (`id_building`) REFERENCES `buildings` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_po_images_room` FOREIGN KEY (`id_room`) REFERENCES `rooms` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_po_images_feature` FOREIGN KEY (`id_feature`) REFERENCES `features` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
